name: jin_widget_helper
description: A fluter package that support variuos UI helper
version: 0.1.1
homepage: https://github.com/Chunlee17/jin_widget_helper

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
