name: jin_widget_helper
description: A package that contain many custom Widget and utility that help decrease your development time on creating custom Widget.
version: 1.5.3+1
homepage: https://github.com/Chunlee17/jin_widget_helper

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
