name: jin_widget_helper
description: A Flutter package that contain many UI and Utility helper that help decrease your development time on creating custom Widget.
version: 1.1.2
homepage: https://github.com/Chunlee17/jin_widget_helper

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  connectivity: ^0.4.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
